import Head from 'next/head';
import Link from 'next/link';
import Header from '@/components/Header';
import { Post } from '../lib/types';
import { getAllPosts } from '../lib/api';

interface HomeProps {
  posts: Post[];
}

export default function Home({ posts }: HomeProps) {
  // 获取所有唯一的标签
  const allTags = Array.from(
    new Set(
      posts
        .flatMap(post => post.tags || [])
        .filter(tag => tag !== undefined)
    )
  );

  return (
    <>
      <Head>
        <title>我的博客</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen bg-gray-50">
        <Header posts={posts || []} />
        <main className="container mx-auto px-4 py-8">
          <div className="flex flex-col md:flex-row">
            {/* 左侧个人资料 */}
            <div className="md:w-1/4 mb-8 md:mb-0 md:mr-8">
              <div className="bg-white rounded-lg shadow p-6">
                <div className="text-center">
                  <div className="bg-gray-200 border-2 border-dashed rounded-xl w-32 h-32 mx-auto mb-4" />
                  <h2 className="text-xl font-bold mb-2">vin-wall</h2>
                  <p className="text-gray-600 mb-4">我是一名普通的开发，通过这个博客，分享一下自己的学习经历和经验。</p>
                </div>
              </div>
              
              {/* 标签分类区域 */}
              {allTags.length > 0 && (
                <div className="bg-white rounded-lg shadow p-6 mt-6">
                  <h3 className="text-lg font-bold mb-4">标签分类</h3>
                  <div className="flex flex-wrap gap-2">
                    {allTags.map((tag, index) => (
                      <Link
                        key={index}
                        href={`/search?q=${encodeURIComponent(tag)}`}
                        className="bg-blue-100 text-blue-800 text-sm font-medium px-3 py-1 rounded-full hover:bg-blue-200 transition-colors"
                      >
                        {tag}
                      </Link>
                    ))}
                  </div>
                </div>
              )}
            </div>

            {/* 右侧文章列表 */}
            <div className="md:w-3/4">
              <h1 className="text-3xl font-bold mb-6">最新文章</h1>
              <div className="space-y-6">
                {Array.isArray(posts) && posts.map((post) => (
                  <div key={post.id} className="bg-white rounded-lg shadow p-6">
                    <h2 className="text-2xl font-bold mb-2">{post.title}</h2>
                    <div className="prose max-w-none mb-4">
                      {post.excerpt}
                    </div>
                    {post.tags && post.tags.length > 0 && (
                      <div className="flex flex-wrap gap-2 mb-4">
                        {post.tags.map((tag, index) => (
                          <Link 
                            key={index} 
                            href={`/search?q=${encodeURIComponent(tag)}`}
                            className="bg-blue-100 text-blue-800 text-xs font-medium px-2.5 py-0.5 rounded hover:bg-blue-200 transition-colors"
                          >
                            {tag}
                          </Link>
                        ))}
                      </div>
                    )}
                    <div className="flex justify-between items-center">
                      <span className="text-sm text-gray-500">{post.date}</span>
                      <Link href={`/posts/${post.id}`} className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded inline-block">
                        阅读全文
                      </Link>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </main>
      </div>
    </>
  );
}

export async function getStaticProps() {
  try {
    const posts = await getAllPosts();
    
    return {
      props: {
        posts: posts || [],
      },
    };
  } catch (error) {
    console.error('Error fetching posts:', error);
    return {
      props: {
        posts: [],
      },
    };
  }
}